// <auto-generated />
using System;
using GreenDragonTrading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenDragonTrading.Infrastructure.Persistence.Migrations.OhlcvMigrations
{
    [DbContext(typeof(OhlcvTimescaleDbContext))]
    [Migration("20260102081127_InitialCreateOhlcv")]
    partial class InitialCreateOhlcv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Ohlcv", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamptz")
                        .HasColumnName("time");

                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ticker");

                    b.Property<string>("Timeframe")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("timeframe");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("close");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("open");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.Property<int?>("TradesCount")
                        .HasColumnType("integer")
                        .HasColumnName("trades_count");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("Time", "Ticker", "Timeframe");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_ohlcv_created_at");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("idx_ohlcv_ticker");

                    b.HasIndex("Time")
                        .IsDescending()
                        .HasDatabaseName("idx_ohlcv_time");

                    b.HasIndex("Ticker", "Timeframe", "Time")
                        .HasDatabaseName("idx_ohlcv_ticker_tf_time");

                    b.ToTable("ohlcv", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
