// <auto-generated />
using System;
using GreenDragonTrading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenDragonTrading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GdtPostgreSqlDbContext))]
    [Migration("20251210042439_AddUserAndSeedInitialData")]
    partial class AddUserAndSeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Exchange", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<decimal>("FirstDayFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("first_day_fluctuation_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NoRightsFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("no_rights_fluctuation_limit");

                    b.Property<decimal>("NormalFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("normal_fluctuation_limit");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Code");

                    b.ToTable("exchanges");

                    b.HasData(
                        new
                        {
                            Code = "HSX",
                            FirstDayFluctuationLimit = 0.20m,
                            Name = "Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh",
                            NoRightsFluctuationLimit = 0.20m,
                            NormalFluctuationLimit = 0.07m,
                            Status = (short)1
                        },
                        new
                        {
                            Code = "HNX",
                            FirstDayFluctuationLimit = 0.30m,
                            Name = "Sở Giao dịch Chứng khoán Hà Nội",
                            NoRightsFluctuationLimit = 0.30m,
                            NormalFluctuationLimit = 0.10m,
                            Status = (short)1
                        },
                        new
                        {
                            Code = "UPCOM",
                            FirstDayFluctuationLimit = 0.40m,
                            Name = "Thị trường UPCoM",
                            NoRightsFluctuationLimit = 0.40m,
                            NormalFluctuationLimit = 0.15m,
                            Status = (short)1
                        });
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("EnName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("en_name");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("parent_id");

                    b.Property<string>("ViName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vi_name");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("sectors");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Symbol", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ticker");

                    b.Property<string>("EnCompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("en_company_name");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("exchange_code");

                    b.Property<string>("Isin")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("isin");

                    b.Property<string>("SectorId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sector_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("TradingStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("trading_status");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<string>("ViCompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vi_company_name");

                    b.HasKey("Ticker");

                    b.HasIndex("ExchangeCode");

                    b.HasIndex("SectorId");

                    b.ToTable("symbols");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6cef9b3f-1f62-4208-b8ab-db44044d7f79"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 12, 10, 4, 24, 39, 519, DateTimeKind.Unspecified).AddTicks(3469), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "greendragon.trading.team@gmail.com",
                            HashedPassword = "96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e",
                            IsEmailVerified = true,
                            PhoneNumber = "0988671875",
                            Role = (short)3,
                            Status = (short)1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Sector", "ParentSector")
                        .WithMany("ChildSectors")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentSector");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Symbol", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Exchange", "Exchange")
                        .WithMany("Symbols")
                        .HasForeignKey("ExchangeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDragonTrading.Domain.Entities.Sector", "Sector")
                        .WithMany("Symbols")
                        .HasForeignKey("SectorId");

                    b.Navigation("Exchange");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Exchange", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.Navigation("ChildSectors");

                    b.Navigation("Symbols");
                });
#pragma warning restore 612, 618
        }
    }
}
