using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GreenDragonTrading.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Creates alerts table if it does not exist.
    /// This migration is idempotent to recover environments where old alert migration missed CreateTable.
    /// </summary>
    public partial class CreateAlertsTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS alerts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    ticker varchar(20) NOT NULL,
    alert_type smallint NOT NULL,
    condition_type smallint NOT NULL,
    threshold_value numeric(18,4) NOT NULL,
    name varchar(255) NULL,
    is_active boolean NOT NULL,
    is_triggered boolean NOT NULL,
    last_triggered_at timestamp with time zone NULL,
    chat_session_id integer NULL,
    message_template jsonb NULL,
    notify_via smallint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT fk_alerts_users_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_alerts_symbols_ticker FOREIGN KEY (ticker) REFERENCES symbols(ticker) ON DELETE NO ACTION
);
");

            migrationBuilder.Sql(@"
CREATE INDEX IF NOT EXISTS ix_alerts_user_id ON alerts(user_id);
CREATE INDEX IF NOT EXISTS ix_alerts_ticker ON alerts(ticker);
CREATE INDEX IF NOT EXISTS ix_alerts_ticker_is_active_is_triggered ON alerts(ticker, is_active, is_triggered);
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS alerts;");
        }
    }
}
