// <auto-generated />
using System;
using GreenDragonTrading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenDragonTrading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GdtPostgreSqlDbContext))]
    [Migration("20260111132815_UpdateFRMoreDetails")]
    partial class UpdateFRMoreDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Exchange", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<decimal>("FirstDayFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("first_day_fluctuation_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NoRightsFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("no_rights_fluctuation_limit");

                    b.Property<decimal>("NormalFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("normal_fluctuation_limit");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Code");

                    b.ToTable("exchanges");

                    b.HasData(
                        new
                        {
                            Code = "HSX",
                            FirstDayFluctuationLimit = 0.20m,
                            Name = "Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh",
                            NoRightsFluctuationLimit = 0.20m,
                            NormalFluctuationLimit = 0.07m,
                            Status = (short)1
                        },
                        new
                        {
                            Code = "HNX",
                            FirstDayFluctuationLimit = 0.30m,
                            Name = "Sở Giao dịch Chứng khoán Hà Nội",
                            NoRightsFluctuationLimit = 0.30m,
                            NormalFluctuationLimit = 0.10m,
                            Status = (short)1
                        },
                        new
                        {
                            Code = "UPCOM",
                            FirstDayFluctuationLimit = 0.40m,
                            Name = "Thị trường UPCoM",
                            NoRightsFluctuationLimit = 0.40m,
                            NormalFluctuationLimit = 0.15m,
                            Status = (short)1
                        });
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.FinancialReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BeginningCash")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("beginning_cash");

                    b.Property<decimal?>("CashAndCashExchangeable")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("cash_and_cash_equivalents");

                    b.Property<decimal?>("CashFromFinancing")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("cash_from_financing");

                    b.Property<decimal?>("CashFromInvesting")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("cash_from_investing");

                    b.Property<decimal?>("CashFromOperating")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("cash_from_operating");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<decimal?>("CostOfGoodsSold")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("cost_of_goods_sold");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("EndingCash")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("ending_cash");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<decimal?>("FinancialExpenses")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("financial_expenses");

                    b.Property<decimal?>("FixedAssets")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("fixed_assets");

                    b.Property<decimal?>("GeneralAndAdministrationExpenses")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("general_and_administration_expenses");

                    b.Property<decimal?>("GrossProfit")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("gross_profit");

                    b.Property<decimal?>("IncomeTaxExpense")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("income_tax_expense");

                    b.Property<decimal?>("Inventories")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("inventories");

                    b.Property<decimal?>("Liabilities")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("liabilities");

                    b.Property<decimal?>("LongTermAssets")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("long_term_assets");

                    b.Property<decimal?>("LongTermLiabilities")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("long_term_liabilities");

                    b.Property<decimal?>("LongTermReceivables")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("long_term_receivables");

                    b.Property<decimal?>("NetCashFlow")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("net_cash_flow");

                    b.Property<decimal?>("NetProfit")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("net_profit");

                    b.Property<decimal?>("NetRevenue")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("net_revenue");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OtherExpense")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("other_expense");

                    b.Property<decimal?>("OtherFunds")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("other_funds");

                    b.Property<decimal?>("OtherIncome")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("other_income");

                    b.Property<decimal?>("OtherProfit")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("other_profit");

                    b.Property<decimal?>("OwnerEquity")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("owner_equity");

                    b.Property<short>("Period")
                        .HasColumnType("smallint")
                        .HasColumnName("period");

                    b.Property<decimal?>("ProfitAfterTax")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("profit_after_tax");

                    b.Property<decimal?>("ProfitBeforeTax")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("profit_before_tax");

                    b.Property<decimal?>("ProvisionForDeclineInInventory")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("provision_for_decline_in_inventory");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("revenue");

                    b.Property<decimal?>("RevenueDeductions")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("revenue_deductions");

                    b.Property<decimal?>("RevenueFromFinancialActivities")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("revenue_from_financial_activities");

                    b.Property<decimal?>("ShortTermAssets")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("short_term_assets");

                    b.Property<decimal?>("ShortTermFinancialInvestments")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("short_term_financial_investments");

                    b.Property<decimal?>("ShortTermLiabilities")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("short_term_liabilities");

                    b.Property<decimal?>("ShortTermReceivables")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("short_term_receivables");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ticker");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("total_assets");

                    b.Property<decimal?>("TotalResources")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("total_resources");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("Status");

                    b.HasIndex("Ticker", "Year", "Period")
                        .IsUnique();

                    b.ToTable("financial_reports", (string)null);
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.FinancialReportItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("financial_report_items", (string)null);
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.FinancialReportValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(20,4)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReportId");

                    b.HasIndex("ReportId", "ItemId")
                        .IsUnique();

                    b.ToTable("financial_report_values", (string)null);
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.ModuleLayout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_default");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("layout_name");

                    b.Property<short>("ModuleType")
                        .HasMaxLength(50)
                        .HasColumnType("smallint")
                        .HasColumnName("module_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsSystemDefault")
                        .HasFilter("\"is_system_default\" = true");

                    b.HasIndex("UserId", "ModuleType");

                    b.ToTable("module_layouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConfigJson = "\r\n        {\r\n          \"state\": {\r\n            \"columns\": {\r\n              \"ticker\": { \"field\": \"ticker\", \"visible\": true, \"width\": 80, \"order\": 0 },\r\n              \"lastPrice\": { \"field\": \"lastPrice\", \"visible\": true, \"width\": 95, \"order\": 10 },\r\n              \"change\": { \"field\": \"change\", \"visible\": true, \"width\": 80, \"order\": 12 },\r\n              \"ratioChange\": { \"field\": \"ratioChange\", \"visible\": true, \"width\": 90, \"order\": 13 },\r\n              \"totalVol\": { \"field\": \"totalVol\", \"visible\": true, \"width\": 120, \"order\": 20 },\r\n              \"PE\": { \"field\": \"PE\", \"visible\": false, \"width\": 80, \"order\": 48 },\r\n              \"ROE\": { \"field\": \"ROE\", \"visible\": false, \"width\": 80, \"order\": 49 }\r\n            }\r\n          }\r\n        }",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 13, 28, 14, 806, DateTimeKind.Unspecified).AddTicks(8825), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSystemDefault = true,
                            LayoutName = "Giao diện bộ lọc mặc định",
                            ModuleType = (short)1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 13, 28, 14, 806, DateTimeKind.Unspecified).AddTicks(8826), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("EnName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("en_name");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("parent_id");

                    b.Property<string>("ViName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vi_name");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("sectors");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_in_days");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("integer")
                        .HasColumnName("level_order");

                    b.Property<int>("MaxLayouts")
                        .HasColumnType("integer")
                        .HasColumnName("max_layouts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18, 2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Symbol", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ticker");

                    b.Property<string>("EnCompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("en_company_name");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("exchange_code");

                    b.Property<string>("Isin")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("isin");

                    b.Property<string>("SectorId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sector_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<short>("TradingStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("trading_status");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<string>("ViCompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vi_company_name");

                    b.HasKey("Ticker");

                    b.HasIndex("ExchangeCode");

                    b.HasIndex("SectorId");

                    b.ToTable("symbols");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "greendragon.trading.team@gmail.com",
                            HashedPassword = "96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e",
                            IsEmailVerified = true,
                            PhoneNumber = "0988671875",
                            Role = (short)3,
                            Status = (short)1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Tickers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tickers");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("watch_lists", (string)null);
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("LayoutJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("layout_json");

                    b.Property<string>("ShareCode")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("share_code");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("workspace_name");

                    b.HasKey("Id");

                    b.HasIndex("ShareCode")
                        .IsUnique()
                        .HasFilter("\"share_code\" IS NOT NULL");

                    b.HasIndex("UserId", "IsDefault")
                        .HasFilter("\"is_default\" = true");

                    b.HasIndex("UserId", "WorkspaceName")
                        .IsUnique();

                    b.ToTable("workspaces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 13, 28, 14, 806, DateTimeKind.Unspecified).AddTicks(8883), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDefault = true,
                            LayoutJson = "{\r\n          \"modules\": [\r\n            {\r\n              \"i\": \"stock-screener-default\",\r\n              \"type\": \"stock-screener\",\r\n              \"title\": \"Bộ lọc cổ phiếu\",\r\n              \"x\": 0, \"y\": 36, \"w\": 96, \"h\": 20,\r\n              \"activeLayoutId\": 1  \r\n            }\r\n          ]\r\n        }",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 11, 13, 28, 14, 806, DateTimeKind.Unspecified).AddTicks(8883), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkspaceName = "SYSTEM_DEFAULT_LAYOUT"
                        });
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.FinancialReport", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("Ticker")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Symbol");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.FinancialReportValue", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.FinancialReportItem", "Item")
                        .WithMany("Values")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenDragonTrading.Domain.Entities.FinancialReport", "Report")
                        .WithMany("Values")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.ModuleLayout", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Sector", "ParentSector")
                        .WithMany("ChildSectors")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentSector");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Symbol", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Exchange", "Exchange")
                        .WithMany("Symbols")
                        .HasForeignKey("ExchangeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDragonTrading.Domain.Entities.Sector", "Sector")
                        .WithMany("Symbols")
                        .HasForeignKey("SectorId");

                    b.Navigation("Exchange");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Subscription", "Subscription")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GreenDragonTrading.Domain.Entities.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.WatchList", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.User", "User")
                        .WithMany("Workspaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Exchange", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.FinancialReport", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.FinancialReportItem", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.Navigation("ChildSectors");

                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.User", b =>
                {
                    b.Navigation("UserSubscriptions");

                    b.Navigation("Workspaces");
                });
#pragma warning restore 612, 618
        }
    }
}
