// <auto-generated />
using System;
using GreenDragonTrading.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenDragonTrading.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GdtPostgreSqlDbContext))]
    partial class GdtPostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Exchange", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<decimal>("FirstDayFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("first_day_fluctuation_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("NoRightsFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("no_rights_fluctuation_limit");

                    b.Property<decimal>("NormalFluctuationLimit")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("normal_fluctuation_limit");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("Code");

                    b.ToTable("exchanges");

                    b.HasData(
                        new
                        {
                            Code = "HSX",
                            FirstDayFluctuationLimit = 0.20m,
                            Name = "Sở Giao dịch Chứng khoán Thành phố Hồ Chí Minh",
                            NoRightsFluctuationLimit = 0.20m,
                            NormalFluctuationLimit = 0.07m,
                            Status = (short)1
                        },
                        new
                        {
                            Code = "HNX",
                            FirstDayFluctuationLimit = 0.30m,
                            Name = "Sở Giao dịch Chứng khoán Hà Nội",
                            NoRightsFluctuationLimit = 0.30m,
                            NormalFluctuationLimit = 0.10m,
                            Status = (short)1
                        },
                        new
                        {
                            Code = "UPCOM",
                            FirstDayFluctuationLimit = 0.40m,
                            Name = "Thị trường UPCoM",
                            NoRightsFluctuationLimit = 0.40m,
                            NormalFluctuationLimit = 0.15m,
                            Status = (short)1
                        });
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("EnName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("en_name");

                    b.Property<int?>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("parent_id");

                    b.Property<string>("ViName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vi_name");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("sectors");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Symbol", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ticker");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<long?>("CharterCapital")
                        .HasColumnType("bigint")
                        .HasColumnName("charter_capital");

                    b.Property<string>("CompanyProfile")
                        .HasColumnType("varchar")
                        .HasColumnName("company_profile");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EnCompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("en_company_name");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("exchange_code");

                    b.Property<string>("Fax")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("fax");

                    b.Property<long?>("FirstPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("first_price");

                    b.Property<DateTime?>("FoundingDate")
                        .HasColumnType("date")
                        .HasColumnName("founding_date");

                    b.Property<string>("Isin")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("isin");

                    b.Property<DateTime?>("ListingDate")
                        .HasColumnType("date")
                        .HasColumnName("listing_date");

                    b.Property<string>("SectorId")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sector_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("Telephone")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("telephone");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<string>("ViCompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vi_company_name");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("website");

                    b.HasKey("Ticker");

                    b.HasIndex("ExchangeCode");

                    b.HasIndex("SectorId");

                    b.ToTable("symbols");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Sector", "ParentSector")
                        .WithMany("ChildSectors")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentSector");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Symbol", b =>
                {
                    b.HasOne("GreenDragonTrading.Domain.Entities.Exchange", "Exchange")
                        .WithMany("Symbols")
                        .HasForeignKey("ExchangeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDragonTrading.Domain.Entities.Sector", "Sector")
                        .WithMany("Symbols")
                        .HasForeignKey("SectorId");

                    b.Navigation("Exchange");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Exchange", b =>
                {
                    b.Navigation("Symbols");
                });

            modelBuilder.Entity("GreenDragonTrading.Domain.Entities.Sector", b =>
                {
                    b.Navigation("ChildSectors");

                    b.Navigation("Symbols");
                });
#pragma warning restore 612, 618
        }
    }
}
